AWSTemplateFormatVersion: "2010-09-09"

Description: >
  This is very simple setup for AWS Directory Service. The directory is exposed via LB and Nginx Proxy.

Parameters:
  CfnS3Bucket:
    Description: Name of S3 Bucket, where we store CloudFormation templates
    Type: String

  DirectoryName:
    Description: Name of the Directory
    Type: String
    Default: my-domain.com
  
  DirectoryPassword:
    Description: Password to access the Directory Service
    Type: String
    NoEcho: true

  VpcCidr:
    Description: CIDR for VPC
    Type: String
    Default: 10.5.0.0/16

Resources:

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${CfnS3Bucket}.s3.amazonaws.com/vpc/vpc.yaml
      Parameters:
        MainStackName: !Ref ${AWS::StackName}
        VpcCidr: !Ref VpcCidr

  LoadBalancers:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${CfnS3Bucket}.s3.amazonaws.com/infrastructure/loadbalancers.yaml
      Parameters:
        MainStackName: !Ref ${AWS::StackName}
        PrivateSubnets: !GetAtt VPC.Outputs.PrivateSubnets
        PublicSubnets: !GetAtt VPC.Outputs.PublicSubnets

  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${CfnS3Bucket}.s3.amazonaws.com/infrastructure/security-groups.yaml
      Parameters:
        MainStackName: !Ref ${AWS::StackName}

  DirectoryServices:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${CfnS3Bucket}.s3.amazonaws.com/directory-service/directory.yaml
      Parameters:
        DirectoryName: !Ref DirectoryName
        DirectoryPassword: !Ref DirectoryPassword
        MainStackName: !Ref ${AWS::StackName}
        Ec2ProxySecurityGroupId: !GetAtt SecurityGroups.Outputs.Ec2ProxySecurityGroupId
        Subnets: !GetAtt VPC.Outputs.PrivateSubnets
        VpcId: !GetAtt VPC.Outputs.MainVpc
